# BUILD stage
FROM maven:3.9.6-eclipse-temurin-21-alpine AS builder

# Set BUILD stage workdir to app folder
WORKDIR /app

# Copy root pom.xml file to workidr folder
COPY pom.xml .

# Copy microservice pom.xml file to corresponding image folder
COPY api-gateway/pom.xml api-gateway/

# Download dependencies as listed in api-gateway/pom.xml file before compilation of the module
RUN mvn -f api-gateway/pom.xml dependency:go-offline -B

# Copy the source code
COPY api-gateway/src api-gateway/src

# Build API-gateway module using mvn
RUN mvn -f api-gateway/pom.xml package -DskipTests -B

# RUN stage
FROM eclipse-temurin:21-jre-alpine AS runner

# FORCED UPDATE OF SYSTEM LIBRARIES
RUN apk update && apk upgrade --no-cache && apk add curl

LABEL maintainer="themarcos" \
      description="MedApp - API Gateway" \
      version="1.0.0"

# First one tells Java that it runs inside container
# Second one tells Java that it can use up to 75% of assigned container memory
ENV JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/./urandom"

# Set RUN stage stage workdir to app folder
WORKDIR /app

# Create both group and user without root privileges
RUN addgroup -S medapp && adduser -S medapp -G medapp

# Copy JAR file from the BUILD stage
COPY --from=builder /app/api-gateway/target/*.jar app.jar

# Change medapp file ownership to medapp
RUN chown medapp:medapp app.jar

# Switch to user medapp
USER medapp

# EXPOSE port 8080 outside the container
EXPOSE 8080

# Run app with JAVA_OPTS parameter
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]