# BUILD stage
FROM node:22-alpine AS builder

# Set BUILD stage workdir to app folder
WORKDIR /app

# Copy package files to workdir
COPY frontend/package*.json .

# Install exact dependencies from lockfile
RUN npm ci --silent

# Copy the source code
COPY frontend/ .

# Build the project for production
RUN npm run build

# RUN stage
FROM nginx:alpine AS runner

LABEL maintainer="themarcos" \
      description="MedApp - Frontend React" \
      version="1.0.0"

# Change system user to root in order to update all packages
USER root
RUN apk update && apk upgrade --no-cache

# Copy build artifacts from the BUILD stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy custom nginx configuration
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

# EXPOSE port 80 outside the container
EXPOSE 80

# Start nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]