apiVersion: v1
kind: ConfigMap
metadata:
  name: medapp-config
  namespace: medapp
data:
  DB_HOST: "mysql-db-service"
  DB_PORT: "3306"
  DB_USER: "medapp_user"

  APPOINTMENT_SERVICE_HOST: "appointment-service"
  APPOINTMENT_SERVICE_PORT: "8082"

  MAIL_PORT: "587"
  MAIL_USER: "studentengineerdb1@gmail.com"

  SPRING_CLOUD_COMPATIBILITY_VERIFIER_ENABLED: "false"
  
  MANAGEMENT_HEALTH_MAIL_ENABLED: "false"

---
apiVersion: v1
kind: Secret
metadata:
  name: medapp-secrets
  namespace: medapp
type: Opaque
stringData:
  DB_ROOT_PASS: "SuperSecureRootPassword123!"
  DB_PASS: "MedAppSecretPassword456!"
  JWT_SECRET: "Tw6v9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdRgUkXp2s5v8y/B?E(H+KbPeShV"
  MAIL_PASS: "pvpxgvqekcbdcwst"